<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEx0jcgh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEx0jcgh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEx0jcgh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEx0jcgh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEx0jcgh\appProdProjectContainer([
    'container.build_hash' => 'Ex0jcgh',
    'container.build_id' => 'ddc87247',
    'container.build_time' => 1574266368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEx0jcgh');
