<?php

namespace BddBundle\Repository;

/**
 * EventCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
