<?php

namespace BddBundle\Repository;

/**
 * PackDescorationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackDecorationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($cat){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM BddBundle:PackDecoration p
                WHERE p.typep = :str'
            )
            ->setParameter('str', $cat)
            ->getResult();
    }
}
