<?php

namespace ProductBundle\Repository;

/**
 * OffrePromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffrePromotionRepository extends \Doctrine\ORM\EntityRepository
{





}
