<?php

namespace ProductBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

public function Topvente(){
    $query = $this->getEntityManager()->createQuery(
        'SELECT SUM() AS nmbreAction , week(a.dateOuverture) AS week,( SELECT COUNT(c.idAction) AS nmbre , week(c.dateOuverture) AS semaine FROM ActionActionBundle:Action c WHERE c.cloture = 0 GROUP BY semaine ) AS nmbreRetard FROM ActionActionBundle:Action a GROUP BY week
                        '
    );
}



}