<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFga2bdv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFga2bdv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFga2bdv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFga2bdv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFga2bdv\appDevDebugProjectContainer([
    'container.build_hash' => 'Fga2bdv',
    'container.build_id' => '1652265f',
    'container.build_time' => 1574888293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFga2bdv');
