<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsitk9l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsitk9l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDsitk9l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDsitk9l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDsitk9l\appDevDebugProjectContainer([
    'container.build_hash' => 'Dsitk9l',
    'container.build_id' => 'eff11faa',
    'container.build_time' => 1574287281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsitk9l');
