<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQu3gqyl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQu3gqyl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQu3gqyl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQu3gqyl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQu3gqyl\appDevDebugProjectContainer([
    'container.build_hash' => 'Qu3gqyl',
    'container.build_id' => '9027be2e',
    'container.build_time' => 1574710918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQu3gqyl');
